### ISSUE TITLE
My device RAM is 3gb when i try to flash recovery through ADB getting error file is too large but when i try to flash zip of 2gb variant it is giving error 69

### ISSUE THREAD

**Issue by AndroiableDroid** [RedWolfRecovery/rw_recovery#1]
when i try to flash using adb it is giving this error:
fastboot flash recovery ~/new/RedWolf-Unofficial-LS5015.imgtarget reported max download size of 268435456 bytes
sending 'recovery' (41064 KB)...
OKAY [  1.307s]
writing 'recovery'...
FAILED (remote: size too large)
finished. total time: 1.308s

**Comment by AndroiableDroid** [comment]
plz fix it

**Comment by danparidae** [comment]
there's nothing to fix. your recovery partition is too small
