### ISSUE TITLE
Recovery touch doesn't work if someone has replaced their screen with an aftermarket one

### ISSUE THREAD

**Issue by 0xConstant1** [RedWolfRecovery/rw_recovery#6]
--

**Comment by Constant-ine** [comment]
Not even a response, so unprofessional, at least add that to the "Warnings:" section of your thread, what if someone replaces their screen and has redwolf installed? Unecessary trouble

**Comment by danparidae** [comment]
we don't care about replaced touchcreen. use original ones. also we're not kenzo-only-related and it will happen 1:1000 times so it's not that important

**Comment by danparidae** [comment]
lmao

pt., 13 kwi 2018, 11:21 użytkownik Constant-ine <notifications@github.com>
napisał:
