### ISSUE TITLE
I can't compile RedWolf.

### ISSUE THREAD

**Issue by nkrapivin** [RedWolfRecovery/rw_recovery#8]
nikita@nikita-Aspire-E1-571G:~/rwq$ mka recoveryimage

PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=8.1.0
TARGET_PRODUCT=omni_santoni
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv7-a-neon
TARGET_2ND_CPU_VARIANT=cortex-a53
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.13.0-43-generic-x86_64-with-Ubuntu-16.04-xenial
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=OPM4.171019.016.B1
OUT_DIR=/home/nikita/rwq/out

[44/44] bootstrap /home/nikita/rwq/out/soong/.minibootstrap/build.ninja.in
[4/4] cp /home/nikita/rwq/out/soong/.bootstrap/bin/bpglob
[452/453] glob vendor/*/*/*/*/*/*/Android.bp
[36/51] test android/soong/cc/config
open : no such file or directory
PASS
[47/51] test android/soong/cc
open : no such file or directory
PASS
[50/51] soong_build docs /home/nikita/rwq/out/soong/.bootstrap/docs/soong_build.html
FAILED: /home/nikita/rwq/out/soong/.bootstrap/docs/soong_build.html 
/home/nikita/rwq/out/soong/.bootstrap/bin/soong_build  -t -b /home/nikita/rwq/out/soong --docs /home/nikita/rwq/out/soong/.bootstrap/docs/soong_build.html ./Android.bp
open : no such file or directory
error: system/hardware/interfaces/wifi/keystore/1.0/vts/functional/Android.bp:17:1: "VtsHalWifiKeystoreV1_0TargetTest" depends on undefined module "VtsHalHidlTargetTestBase"
error: frameworks/av/media/ndk/Android.bp:34:1: "libmediandk" depends on undefined module "libmedia_jni"
error: frameworks/av/media/ndk/Android.bp:34:1: "libmediandk" depends on undefined module "libskia"
error: frameworks/av/media/ndk/Android.bp:34:1: "libmediandk" depends on undefined module "libandroid"
error: frameworks/av/media/ndk/Android.bp:34:1: "libmediandk" depends on undefined module "libandroid_runtime"
error: frameworks/hardware/interfaces/displayservice/1.0/vts/functional/Android.bp:17:1: "VtsFwkDisplayServiceV1_0TargetTest" depends on undefined module "VtsHalHidlTargetTestBase"
error: frameworks/av/media/libstagefright/http/Android.bp:1:1: "libstagefright_http_support" depends on undefined module "libandroid_runtime"
error: frameworks/av/media/libstagefright/codecs/mpeg2dec/Android.bp:1:1: "libstagefright_soft_mpeg2dec" depends on undefined module "libmpeg2dec"
error: frameworks/av/media/libstagefright/codecs/gsm/dec/Android.bp:1:1: "libstagefright_soft_gsmdec" depends on undefined module "libgsm"
error: system/hardware/interfaces/net/netd/1.0/vts/functional/Android.bp:1:1: "VtsHalNetNetdV1_0TargetTest" depends on undefined module "VtsHalHidlTargetTestBase"
error: frameworks/av/drm/mediadrm/plugins/clearkey/Android.bp:17:1: "libdrmclearkeyplugin" depends on undefined module "libjsmn"
error: hardware/interfaces/media/omx/1.0/vts/functional/common/Android.bp:17:1: "VtsHalMediaOmxV1_0CommonUtil" depends on undefined module "VtsHalHidlTargetTestBase"
error: frameworks/av/media/libstagefright/codecs/aacdec/Android.bp:1:1: "libstagefright_soft_aacdec" depends on undefined module "libFraunhoferAAC"
error: frameworks/av/media/libstagefright/codecs/vorbis/dec/Android.bp:1:1: "libstagefright_soft_vorbisdec" depends on undefined module "libvorbisidec"
error: frameworks/av/media/libstagefright/colorconversion/Android.bp:1:1: "libstagefright_color_conversion" depends on undefined module "libyuv_static"
error: frameworks/av/media/libstagefright/codecs/on2/dec/Android.bp:1:1: "libstagefright_soft_vpxdec" depends on undefined module "libvpx"
error: frameworks/av/media/libstagefright/Android.bp:7:1: "libstagefright" depends on undefined module "libyuv_static"
error: frameworks/av/media/libstagefright/Android.bp:7:1: "libstagefright" depends on undefined module "libvpx"
error: frameworks/av/media/libstagefright/Android.bp:7:1: "libstagefright" depends on undefined module "libwebm"
error: frameworks/av/media/libstagefright/Android.bp:7:1: "libstagefright" depends on undefined module "libsonivox"
error: frameworks/av/media/libstagefright/Android.bp:7:1: "libstagefright" depends on undefined module "libvorbisidec"
error: frameworks/av/media/libstagefright/codecs/aacenc/Android.bp:113:1: "libstagefright_soft_aacenc" depends on undefined module "libFraunhoferAAC"
error: frameworks/native/services/inputflinger/tests/Android.bp:3:1: "inputflinger_tests" depends on undefined module "libskia"
error: frameworks/native/services/inputflinger/tests/Android.bp:3:1: "inputflinger_tests" depends on undefined module "libinputservice"
error: frameworks/av/media/libstagefright/codecs/avcdec/Android.bp:1:1: "libstagefright_soft_avcdec" depends on undefined module "libavcdec"
error: hardware/interfaces/wifi/1.0/vts/functional/Android.bp:17:1: "VtsHalWifiV1_0TargetTestUtil" depends on undefined module "VtsHalHidlTargetTestBase"
error: frameworks/av/media/libstagefright/codecs/opus/dec/Android.bp:1:1: "libstagefright_soft_opusdec" depends on undefined module "libopus"
error: frameworks/av/media/libstagefright/codecs/on2/enc/Android.bp:1:1: "libstagefright_soft_vpxenc" depends on undefined module "libvpx"
error: frameworks/av/media/libstagefright/codecs/avcenc/Android.bp:1:1: "libstagefright_soft_avcenc" depends on undefined module "libavcenc"
error: frameworks/av/media/libstagefright/codecs/hevcdec/Android.bp:1:1: "libstagefright_soft_hevcdec" depends on undefined module "libhevcdec"
[51/51] /home/nikita/rwq/out/soong/.bootstrap/bin/soong_build /home/nikita/rwq/out/soong/build.ninja
FAILED: /home/nikita/rwq/out/soong/build.ninja 
/home/nikita/rwq/out/soong/.bootstrap/bin/soong_build  -t -b /home/nikita/rwq/out/soong -d /home/nikita/rwq/out/soong/build.ninja.d -o /home/nikita/rwq/out/soong/build.ninja Android.bp
open : no such file or directory
error: frameworks/hardware/interfaces/displayservice/1.0/vts/functional/Android.bp:17:1: "VtsFwkDisplayServiceV1_0TargetTest" depends on undefined module "VtsHalHidlTargetTestBase"
error: system/hardware/interfaces/wifi/keystore/1.0/vts/functional/Android.bp:17:1: "VtsHalWifiKeystoreV1_0TargetTest" depends on undefined module "VtsHalHidlTargetTestBase"
error: frameworks/av/media/ndk/Android.bp:34:1: "libmediandk" depends on undefined module "libmedia_jni"
error: frameworks/av/media/ndk/Android.bp:34:1: "libmediandk" depends on undefined module "libskia"
error: frameworks/av/media/ndk/Android.bp:34:1: "libmediandk" depends on undefined module "libandroid"
error: frameworks/av/media/ndk/Android.bp:34:1: "libmediandk" depends on undefined module "libandroid_runtime"
error: frameworks/native/services/inputflinger/tests/Android.bp:3:1: "inputflinger_tests" depends on undefined module "libskia"
error: frameworks/native/services/inputflinger/tests/Android.bp:3:1: "inputflinger_tests" depends on undefined module "libinputservice"
error: frameworks/av/media/libstagefright/codecs/hevcdec/Android.bp:1:1: "libstagefright_soft_hevcdec" depends on undefined module "libhevcdec"
error: frameworks/av/media/libstagefright/codecs/avcenc/Android.bp:1:1: "libstagefright_soft_avcenc" depends on undefined module "libavcenc"
error: hardware/interfaces/media/omx/1.0/vts/functional/common/Android.bp:17:1: "VtsHalMediaOmxV1_0CommonUtil" depends on undefined module "VtsHalHidlTargetTestBase"
error: frameworks/av/media/libstagefright/codecs/on2/enc/Android.bp:1:1: "libstagefright_soft_vpxenc" depends on undefined module "libvpx"
error: frameworks/av/media/libstagefright/Android.bp:7:1: "libstagefright" depends on undefined module "libyuv_static"
error: frameworks/av/media/libstagefright/Android.bp:7:1: "libstagefright" depends on undefined module "libvpx"
error: frameworks/av/media/libstagefright/Android.bp:7:1: "libstagefright" depends on undefined module "libwebm"
error: frameworks/av/media/libstagefright/Android.bp:7:1: "libstagefright" depends on undefined module "libsonivox"
error: frameworks/av/media/libstagefright/Android.bp:7:1: "libstagefright" depends on undefined module "libvorbisidec"
error: frameworks/av/media/libstagefright/codecs/avcdec/Android.bp:1:1: "libstagefright_soft_avcdec" depends on undefined module "libavcdec"
error: system/hardware/interfaces/net/netd/1.0/vts/functional/Android.bp:1:1: "VtsHalNetNetdV1_0TargetTest" depends on undefined module "VtsHalHidlTargetTestBase"
error: hardware/interfaces/wifi/1.0/vts/functional/Android.bp:17:1: "VtsHalWifiV1_0TargetTestUtil" depends on undefined module "VtsHalHidlTargetTestBase"
error: frameworks/av/media/libstagefright/codecs/vorbis/dec/Android.bp:1:1: "libstagefright_soft_vorbisdec" depends on undefined module "libvorbisidec"
error: frameworks/av/media/libstagefright/colorconversion/Android.bp:1:1: "libstagefright_color_conversion" depends on undefined module "libyuv_static"
error: frameworks/av/media/libstagefright/http/Android.bp:1:1: "libstagefright_http_support" depends on undefined module "libandroid_runtime"
error: frameworks/av/media/libstagefright/codecs/aacdec/Android.bp:1:1: "libstagefright_soft_aacdec" depends on undefined module "libFraunhoferAAC"
error: frameworks/av/media/libstagefright/codecs/on2/dec/Android.bp:1:1: "libstagefright_soft_vpxdec" depends on undefined module "libvpx"
error: frameworks/av/media/libstagefright/codecs/gsm/dec/Android.bp:1:1: "libstagefright_soft_gsmdec" depends on undefined module "libgsm"
error: frameworks/av/media/libstagefright/codecs/mpeg2dec/Android.bp:1:1: "libstagefright_soft_mpeg2dec" depends on undefined module "libmpeg2dec"
error: frameworks/av/media/libstagefright/codecs/aacenc/Android.bp:113:1: "libstagefright_soft_aacenc" depends on undefined module "libFraunhoferAAC"
error: frameworks/av/drm/mediadrm/plugins/clearkey/Android.bp:17:1: "libdrmclearkeyplugin" depends on undefined module "libjsmn"
error: frameworks/av/media/libstagefright/codecs/opus/dec/Android.bp:1:1: "libstagefright_soft_opusdec" depends on undefined module "libopus"
ninja: build stopped: subcommand failed.
18:19:49 soong failed with: exit status 1

#### failed to build some targets (16 seconds) ####

nikita@nikita-Aspire-E1-571G:~/rwq$

**Comment by danparidae** [comment]
your device tree isn't updated to 8.1. try using rw-n branch

**Comment by nkrapivin** [comment]
How can I update device tree?

**Comment by dadi11** [comment]
if you don't know how then you won't do it. it's not a place for a programming lessons. if your device hasn't got 8.1 branch then use rw-n as I said.

**Comment by danparidae** [comment]
if you don't know how then you won't do it. it's not a place for a programming lessons. if your device hasn't got 8.1 branch then use rw-n as I said.

**Comment by ghost** [comment]
`export ALLOW_MISSING_DEPENDENCIES=true` is what you need
